/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AttachmentFileTypeIcon: typeof import('./src/components/icon/AttachmentFileTypeIcon.vue')['default']
        ImageDetailModal: typeof import('./src/components/image/ImageDetailModal.vue')['default']
        ImagePermalinkList: typeof import('./src/components/image/ImagePermalinkList.vue')['default']
        ImageUploadModal: typeof import('./src/components/image/ImageUploadModal.vue')['default']
        ImgtpSelectorProvider: typeof import('./src/components/ImgtpSelectorProvider.vue')['default']
        LazyImage: typeof import('./src/components/image/LazyImage.vue')['default']
        LskySelectorProvider: typeof import('./src/components/LskySelectorProvider.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SmmsSelectorProvider: typeof import('./src/components/SmmsSelectorProvider.vue')['default']
    }
}
